### PR TITLE
Fix missing range checks

### LINKED ISSUE #22: Panic when decoding bech32 string containing an uppercase 'O'
Fuzz tests in rust-bitcoin/rust-bitcoin#100 uncovered the bug that if the bech32 data part contains an uppercase 'O' the parser panics. This is due to insufficient checks that only check the lowercase variants of the forbidden characters (before normalizing them to their lowercase variant):

```rust
if b == b'1' || b == b'b' || b == b'i' || b == b'o' {
    return Err(Error::InvalidChar(b))
}
```

To avoid such issues in the future I will have a look at fuzz testing this crate (#21).

### PR DESCRIPTION
**Pull request by sgeisler**
Fixes #22. 

## TODO:

- [x] rewrite `from_str_lenient` to catch all bad characters
- [x] adapt tests that use `Error::InvalidChar` since its signature was updated
- [x] validate that all bad characters are `-1` in `CHARSET_REV`
- [x] write tests to show the bug is fixed
- [x] have a look at the checks for mixed case, they seem overly complicated

### CODE REVIEW

**Comment by sgeisler** [comment]
The tests fail due to rustup issues with nightly: rust-lang/rust#51699.

File: src/lib.rs [hunk 1]
```diff
@@ -242,34 +243,28 @@ impl Bech32 {
...
-            if b >= b'a' && b <= b'z' {
+
+            if c.is_lowercase() {
                 has_lower = true;
+            } else if c.is_uppercase() {
+                has_upper = true;
             }
 
-            // Uppercase
-            let c = if b >= b'A' && b <= b'Z' {
```
Comment (tamasblummer) [inline src/lib.rs]: was dropping conversion to lower case intentional?

Comment (clarkmoody) [reply src/lib.rs]: I like this use of `CHARSET_REV` in testing for proper range.

File: src/lib.rs [hunk 2]
```diff
@@ -242,34 +243,28 @@ impl Bech32 {
...
+        let mut data_bytes = raw_data.chars().map(|c| {
+            // Only check if c is in the ASCII range, all invalid ASCII characters have the value -1
+            // in CHARSET_REV (which covers the whole ASCII range) and will be filtered out later.
+            if !c.is_ascii() {
+                return Err(Error::InvalidChar(c))
             }
-            // Lowercase
-            if b >= b'a' && b <= b'z' {
+
+            if c.is_lowercase() {
```
Comment (sgeisler) [inline src/lib.rs]: The `is_lowercase` and `is_uppercase` functions are probably slower (since they work for all Unicode characters) than the simple range checks used before, but they seem so much more idiomatic. The ascii-equivalent (`is_ascii_lowercase`) is still `nightly`-only, so if we wanted to avoid handwritten range checks we had to use our own trait for that. But I don't see the need for such optimizations right now.

File: src/lib.rs [hunk 3]
```diff
@@ -242,34 +243,28 @@ impl Bech32 {
...
                 has_lower = true;
```
Comment (sgeisler) [inline src/lib.rs]: I didn't find a better (and preferably shorter/simpler) way of doing the checks for "all characters have the same case". At least none that doesn't need some bigger refactoring of the HRP processing, so I will leave it for now and maybe open another PR dedicated to refactoring.

**Comment by sgeisler** [comment]
Since this seems to be only an internal bug fix I increased the version from `0.4.1` to `0.4.2`. Can anyone review the changes, please? @clarkmoody @tamasblummer

File: src/lib.rs [hunk 4]
```diff
@@ -402,7 +397,7 @@ pub enum Error {
     /// The data or human-readable part is too long or too short
     InvalidLength,
     /// Some part of the string contains an invalid character
-    InvalidChar(u8),
+    InvalidChar(char),
```
Comment (clarkmoody) [inline src/lib.rs]: Is this enum variant change a breaking change that needs a major version bump?

File: src/lib.rs (hunk 2 above)
Comment (clarkmoody) [reply src/lib.rs]: The implementation of `is_lowercase` is:
```rust
    pub fn is_lowercase(self) -> bool {
        match self {
            'a'...'z' => true,
            c if c > '\x7f' => derived_property::Lowercase(c),
            _ => false,
        }
    }
```
So for ASCII characters, it should be fairly performant. `is_uppercase` has a similar structure.

File: src/lib.rs (hunk 4 above)
Comment (sgeisler) [reply src/lib.rs]: Good catch, sorry, I will have to bump the version to `0.5.0`. Would you generally agree that it's better to process unicode strings char-wise instead of their UTF-8 representation byte-wise? Because this change is what made this API break necessary.

**Comment by clarkmoody** [comment]
Pushed `0.5.0` to crates.io
